package resolvers

import (
	"github.com/yourusername/air-go/internal/db"
)

// This file will NOT be regenerated by gqlgen
// It sets up the base Resolver struct that the generated code uses

// Resolver holds dependencies for GraphQL resolvers (T088)
type Resolver struct {
	// Database client for health monitoring and data access
	DBClient *db.Client
}
