package resolvers

import (
	"context"

	"github.com/yourusername/air-go/internal/db"
)

// This file will NOT be regenerated by gqlgen
// It sets up the base Resolver struct that the generated code uses

// DBClient interface for database operations (enables testing with mocks)
type DBClient interface {
	HealthStatus(ctx context.Context) (*db.HealthStatus, error)
	Collection(name string) db.Collection
	IsConnected() bool
}

// Ensure *db.Client implements DBClient interface
var _ DBClient = (*db.Client)(nil)

// Resolver holds dependencies for GraphQL resolvers (T088)
type Resolver struct {
	// Database client for health monitoring and data access
	DBClient DBClient
}
