package resolvers

// This file will NOT be regenerated by gqlgen
// It sets up the base Resolver struct that the generated code uses

type Resolver struct {
	// Add any dependencies your resolvers need here
	// For example: database connections, services, etc.
}
